spring:
  profiles:
    active: local
    group:
      local: console-logging
      prod: prod-config, file-info-logging, file-error-logging, slack-prod-error-logging
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  h2:
    console:
      enabled: true
      path: /h2
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/somawiki
    username: sa
    password:
logging:
  level:
    hibernate: info
server:
  forward-headers-strategy: framework
swagger-docs:
  url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  file:
    path: /home/ubuntu/soma-wiki-project
swagger-docs:
  url: https://soma-wiki.kro.kr
---
springdoc:
  swagger-ui:
    path: index.html